DROP SCHEMA IF EXISTS categoriz;
CREATE SCHEMA categoriz;
USE categoriz;

CREATE TABLE category
(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
name_ VARCHAR(45) NOT NULL,
color INT NOT NULL,
date_ DATE NOT NULL

);